main : com.clashwars.cwutils.CWUtils
name: CWUtils
version: 1.0
description: Bunch of utilities and random useful stuff.
softdepend: [Factions, Essentials]
commands:
    reward:
        description: Give a random reward.
    alts:
        description: Check alts.
    queue:
        description: Add queue msg/cmd
    event:
        description: Event data and join events.