main : com.clashwars.cwutils.CWUtils
name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
softdepend: [Factions, Essentials]
commands:
    reward:
        description: Give a random reward.
    eventreward:
        description: Give a random reward for winning a event.
    alts:
        description: Check alts.
    queue:
        description: Add queue msg/cmd
    event:
        description: Event data and join events.
    vote:
        description: See voting information and links.