name: CWUtils
main: com.clashwars.cwutils.bukkit.CWUtilsPlugin
version: '1.0'
author: ClashWars
description: ClashWars Utils plugin
commands:
    reward:
        description: Give a random reward.
    alts:
        description: Check alts.