name: CWUtils
main: com.clashwars.cwutils.bukkit.CWUtilsPlugin
version: '1.0'
author: ClashWars
description: ClashWars Utils plugin
softdepend: [Factions, Essentials]
commands:
    reward:
        description: Give a random reward.
    alts:
        description: Check alts.
    queue:
        description: Add queue msg/cmd
    event:
        description: Event data and join events.